version: '3.8'

services:
  postgres:
    image: postgres:15
    environment:
      POSTGRES_DB: ecommerce
      POSTGRES_USER: postgres  # sample DB user
      POSTGRES_PASSWORD: pgpass007 # sample password
    ports:
      - "5432:5432"
    volumes:
      - pg_data:/var/lib/postgresql/data

  spark_app:
    build: .
    volumes:
      - ./ecommerce_events:/app/ecommerce_events  # Local folder for new CSV files
    depends_on:
      - postgres
    environment:
      - PYSPARK_PYTHON=python3
    restart: always

volumes:
  pg_data:
